# Generated by Django 5.2.3 on 2025-07-04 12:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='admin_user', max_length=150, null=True, unique=True)),
                ('password', models.CharField(blank=True, default='default_password123', max_length=128, null=True)),
                ('admin_name', models.CharField(blank=True, default='Default Admin', max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, default='0000000000', max_length=15, null=True)),
                ('email_id', models.EmailField(blank=True, default='admin@example.com', max_length=255, null=True, unique=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintType',
            fields=[
                ('complain_id', models.AutoField(primary_key=True, serialize=False)),
                ('complain', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentDetails',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('department_status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ITTeam',
            fields=[
                ('it_team_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=255, null=True)),
                ('create_dt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintDescription',
            fields=[
                ('complain_desc_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10, null=True)),
                ('complain_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_support.complainttype')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('system_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=255, null=True)),
                ('user_create_id', models.IntegerField(blank=True, null=True)),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_support.departmentdetails')),
            ],
        ),
        migrations.CreateModel(
            name='UserComplain',
            fields=[
                ('user_complain_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_id', models.EmailField(blank=True, max_length=255, null=True)),
                ('complain_dt', models.DateField(blank=True, null=True)),
                ('complain_time', models.TimeField(blank=True, null=True)),
                ('resolve_dt', models.DateField(blank=True, null=True)),
                ('resolve_time', models.CharField(blank=True, max_length=50, null=True)),
                ('complain_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Pending', max_length=20, null=True)),
                ('complain_desc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_support.complaintdescription')),
                ('complain_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_support.complainttype')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_support.departmentdetails')),
                ('it_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_support.itteam')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_support.userdetails')),
            ],
        ),
    ]
