# Generated by Django 5.2.3 on 2025-07-07 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='user_create_id',
        ),
    ]
